name: Build and Run C++ Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y cmake g++

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run the server
        run: |
          cd build
          ./cpp_website
